In [2]:
import pandas as pd

df = pd.read_csv('data/steam_reviews_last180days.csv')
df.head()

C:\Users\Playdata\AppData\Local\Temp\ipykernel_43000\3484100119.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/steam_reviews_last180days.csv')

,Unnamed: 0,appid,recommendationid,steamid,num_games_owned,num_reviews_author,playtime_forever,playtime_last_two_weeks,playtime_at_review,deck_playtime_at_review,...,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,developer_response,timestamp_dev_responded,primarily_steam_deck
0,0,1049590,215253495,76561199088477441,0,1,110791.0,2184.0,110700.0,NaN,...,0,0,0.5,0,False,False,False,NaN,NaN,False
1,1,1049590,215244780,76561199111467010,0,1,150415.0,3971.0,150415.0,NaN,...,0,0,0.5,0,False,False,False,NaN,NaN,False
2,2,1049590,215236053,76561198053918088,250,29,4731.0,4731.0,4584.0,NaN,...,0,0,0.5,0,False,False,False,NaN,NaN,False
3,3,1049590,215234263,76561199082041003,0,4,31541.0,1621.0,31541.0,NaN,...,0,0,0.5,0,False,False,False,NaN,NaN,False
4,4,1049590,215231231,76561199072083040,0,1,43106.0,1808.0,43067.0,NaN,...,0,0,0.5,0,False,False,False,NaN,NaN,False

In [4]:
import pandas as pd

game_df = pd.read_csv('data/steam_game_info.csv')
game_df.head()

,appid,required_age,price,metacritic_score,achievements,supported_languages,user_score,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent,genre,price_missing,metacritic_missing,user_score_missing,pct_pos_recent_missing
0,730,0.0,FREE,87.0,1.0,"Czech, Danish, Dutch, English * , Finnish, Fre...",85.694959,85.694959,4859224,85.694959,4859224,"['Action', 'Free To Play']",0,1,0,0
1,1049590,0.0,FREE,87.0,0.0,"English * , Japanese * , Simplified Chinese, K...",81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
2,578080,13.0,FREE,87.0,37.0,"English, Korean, Simplified Chinese, French, G...",55.724266,55.724266,1754094,55.724266,1754094,"['Action', 'Adventure', 'Massively Multiplayer...",0,1,0,0
3,3564740,0.0,FREE,87.0,34.0,"English * , Japanese, Simplified Chinese * , T...",89.684511,89.684511,0,89.684511,0,"['Action', 'Adventure', 'RPG', 'Free To Play']",0,1,1,1
4,3557620,0.0,FREE,87.0,0.0,"English, Traditional Chinese, Thai, Korean * *...",89.684511,89.684511,0,89.684511,0,"['Adventure', 'Casual', 'RPG', 'Strategy', 'Fr...",0,1,1,1

In [5]:
new_df = pd.merge(df, game_df, on='appid', how='left')
new_df

,Unnamed: 0,appid,recommendationid,steamid,num_games_owned,num_reviews_author,playtime_forever,playtime_last_two_weeks,playtime_at_review,deck_playtime_at_review,...,user_score,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent,genre,price_missing,metacritic_missing,user_score_missing,pct_pos_recent_missing
0,0,1049590,215253495,76561199088477441,0,1,110791.0,2184.0,110700.0,NaN,...,81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
1,1,1049590,215244780,76561199111467010,0,1,150415.0,3971.0,150415.0,NaN,...,81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
2,2,1049590,215236053,76561198053918088,250,29,4731.0,4731.0,4584.0,NaN,...,81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
3,3,1049590,215234263,76561199082041003,0,4,31541.0,1621.0,31541.0,NaN,...,81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
4,4,1049590,215231231,76561199072083040,0,1,43106.0,1808.0,43067.0,NaN,...,81.308411,81.308411,107,81.308411,107,"['Indie', 'Strategy', 'Free To Play']",0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940046,1940046,1551360,199409325,76561198893832215,33,4,765.0,0.0,205.0,NaN,...,89.280232,89.280232,238410,89.280232,238410,"['Action', 'Adventure', 'Racing', 'Simulation'...",0,1,0,0
1940047,1940047,1551360,199408610,76561198247480788,0,8,6006.0,0.0,1439.0,NaN,...,89.280232,89.280232,238410,89.280232,238410,"['Action', 'Adventure', 'Racing', 'Simulation'...",0,1,0,0
1940048,1940048,1551360,199407968,76561199827871400,5,1,6746.0,0.0,6165.0,NaN,...,89.280232,89.280232,238410,89.280232,238410,"['Action', 'Adventure', 'Racing', 'Simulation'...",0,1,0,0
1940049,1940049,1551360,199407697,76561199018607695,0,4,21187.0,175.0,13344.0,NaN,...,89.280232,89.280232,238410,89.280232,238410,"['Action', 'Adventure', 'Racing', 'Simulation'...",0,1,0,0
1940050,1940050,1551360,199406694,76561198797856995,21,1,5818.0,167.0,1599.0,NaN,...,89.280232,89.280232,238410,89.280232,238410,"['Action', 'Adventure', 'Racing', 'Simulation'...",0,1,0,0

In [6]:
new_df.to_csv('steam_review_with_gameinfo.csv')

In [7]:
new_df.count()

Unnamed: 0                     1940051
appid                          1940051
recommendationid               1940051
steamid                        1940051
num_games_owned                1940051
num_reviews_author             1940051
playtime_forever               1940039
playtime_last_two_weeks        1940039
playtime_at_review             1939265
deck_playtime_at_review          33209
last_played                    1940039
language                       1940051
review                         1933653
timestamp_created              1940051
timestamp_updated              1940051
voted_up                       1940051
votes_up                       1940051
votes_funny                    1940051
weighted_vote_score            1940051
comment_count                  1940051
steam_purchase                 1940051
received_for_free              1940051
written_during_early_access    1940051
developer_response                4246
timestamp_dev_responded           4246
primarily_steam_deck           1940051
required_age                   1940051
price                          1940051
metacritic_score               1940051
achievements                   1940051
supported_languages            1940051
user_score                     1940051
pct_pos_total                  1940051
num_reviews_total              1940051
pct_pos_recent                 1940051
num_reviews_recent             1940051
genre                          1940051
price_missing                  1940051
metacritic_missing             1940051
user_score_missing             1940051
pct_pos_recent_missing         1940051
dtype: int64